export const POST_LOGIN_DATA_REQUEST = "POST_LOGIN_DATA_REQUEST"
export const POST_LOGIN_DATA_SUCCESS = "POST_LOGIN_DATA_SUCCESS"
export const POST_LOGIN_DATA_FAILURE = "POST_LOGIN_DATA_FAILURE"

export const NEW_POST_REQUEST = "NEW_POST_REQUEST"
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS"
export const NEW_POST_FAILURE = "NEW_POST_FAILURE"

export const FETCH_POST_DATA_REQUEST = "FETCH_POST_DATA_REQUEST"
export const FETCH_POST_DATA_SUCCESS = "FETCH_POST_DATA_SUCCESS"
export const FETCH_POST_DATA_FAILURE = "FETCH_POST_DATA_FAILURE"

export const POST_LIKE_REQUEST = "POST_LIKE_REQUEST"
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS"
export const POST_LIKE_FAILURE = "POST_LIKE_FAILURE"

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST"
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE"

